GET http://localhost:3000/api/repos
###

GET http://localhost:3000/api/repos/6

###

POST http://localhost:3000/api/repos HTTP/1.1
content-type: application/json

{
  "description": "Super pepepepe",
	"name": 125,
	"url": "https://github.com/EmiLy-Ly-san/EmiLy-Ly-san"
}

###

DELETE http://localhost:3000/api/repos/6 HTTP/1.1