GET http://localhost:3000/api/repos
###

GET http://localhost:3000/api/repos/9

###

POST http://localhost:3000/api/repos HTTP/1.1
content-type: application/json

{
  "description": "Super pepepepe",
	"name": "coucou",
	"url": "https://github.com/EmiLy-Ly-san/EmiLy-Lycd",
	"isPrivate": true,
  "languages": [
    {
      "size": 0,
      "node": {}
    }
  ]
}

###

DELETE http://localhost:3000/api/repos/2 HTTP/1.1

###
PUT http://localhost:3000/api/repos/2 HTTP/1.1
content-type: application/json

{
  "description": "Super Em",
	"name": "Coucou",
	"url": "https://github.com/EmiLy-Ly-san/EmiLy-Ly-san"
}

###
GET http://localhost:3000/api/languages